### PR TITLE
Add infra as code landing page

### PR DESCRIPTION
**Pull request by zchase**
## Problem description
We are currently ranking on the second page of Google for the term "infrastructure as code" which is pointing to our homepage. We should create an a landing page for the term, i.e. https://pulumi.com/infrastructure-as-code.

Relevant issue: https://github.com/pulumi/docs/issues/2509

### CODE REVIEW

**Comment by joeduffy** [comment]
This warrants a bit of a deeper discussion. I'm fine starting with what we've got here, however a major thing we want to do with this page is describe what _modern_ IaC means. And for that we need to articulate what that means to us and why we think our approach is differentiated as a result.

**Comment by cnunciato** [comment]
@zchase do you want to close this or revisit it?

**Comment by zchase** [comment]
@cnunciato We want this because if ever change the home page messaging to be something other than "Infrastructure as Code" then we would lose the SEO ranking. For example, if we end up moving to a more "Cloud Engineering" based message.

**Comment by cnunciato** [comment]
@zchase OK, thanks. Do you plan on picking this back up and resubmitting, then? I was mainly asking in light of its age, unmerged status and Joe's question.

**Comment by cnunciato** [comment]
Still keep, or close and move to pulumi-hugo?

**Comment by susanev** [comment]
@zchase do we still need to keep this pr around?

**Pull request closed without merging**
