### PR TITLE
Add docs for Terraform package

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
@justinvp Do I need to do anything else here to get this stuff into the ToC since it is a new package?

**Comment by justinvp** [comment]
@ellismg, you'll need to add the following below [these lines in `config.toml`](https://github.com/pulumi/docs/blob/5c3ab26d28ae18c1f844e10ce3f0b69607b3d817/config.toml#L204-L207):

```toml
[[menu.reference]]
    parent = "node"
    name = "terraform"
    url = "/reference/pkg/nodejs/pulumi/terraform/"
```

It'd also be good to add it to this map to get nicer links to GitHub: https://github.com/pulumi/docs/blob/5c3ab26d28ae18c1f844e10ce3f0b69607b3d817/tools/tscdocgen/main.go#L165

**Comment by justinvp** [comment]
The build failure looks like just an intermittent network issue (broken link checker failed on https://aws.amazon.com/lambda/, but it works for me).

**Comment by ellismg** [comment]
Applied your feedback, @justinvp, PTAL.

**Pull request merged**
