### PR TITLE
Document MacPorts install option

### PR DESCRIPTION
**Pull request by lhaeger**
### Proposed changes

Document MacPorts install option

### CODE REVIEW

**Comment by cnunciato** [comment]
@davidwrede Would you like to pull this in? If so, we'll need to move it to https://github.com/pulumi/pulumi-hugo.

**Comment by davidwrede** [comment]
@cnunciato Assuming this is an officially supported install option, then yeah, we should move it to pulumi-hugo. I'll try and do that before the end of the week.

**Comment by leezen** [comment]
@davidwrede It's a community-supported installation mechanism. It's been up to date on our versions since this PR was submitted, so I think we should bring this in.

**Comment by davidwrede** [comment]
Thanks for the contribution, @lhaeger!

This change is now tracked over in https://github.com/pulumi/pulumi-hugo/pull/33.

**Pull request closed without merging**
