### PR TITLE
feat: statically generate python docs using sphinx + rtd

### PR DESCRIPTION
**Pull request by kpitzen**
This PR is intended to be the first three tasks for this issue:
https://github.com/pulumi/docs/issues/6426
The plan is to only replace the existing python doc links once we've verified this new set of documentation accomplishes what we're setting out to do.  Once that's done, we can remove the current-state documentation as well.

### CODE REVIEW

**Comment by kpitzen** [comment]
The new version of the docs is available here: http://pulumi-docs-origin-pr-8110-486f143b.s3-website.us-west-2.amazonaws.com/docs/reference/pkg/python/providers/pulumi/

**Comment by susanev** [comment]
@kpitzen can you do a search for links to the sdk docs, and update the links to the new version?
for example this page has a link to them `docs/intro/languages/python/` that's not going to the new ones
and the link under reference > pulumi sdk in the left nav is also not going to them; nor is the link on the pulumi sdk landing page

or were you doing a soft launch of these? i think its prolly gonna be confusing to have both around.. am i missing something? maybe adding a description to the pr may help.

**Comment by kpitzen** [comment]
Morning @susanev !  After chatting with @cnunciato about this, the plan was to do this in stages - the first being to simply add the new documentation alongside the old (without updating links, etc) since those links exist both here and in `pulumi-hugo`.  The followup steps would be replacing existing links with the new locations, and finally removing the old docs from this repo.  I wasn't familiar with the description template on this repo, but I'm happy to fill that in as well!

**Comment by susanev** [comment]
@kpitzen cool, sounds good! would suggest adding some deets to the description so reviewers have access to this information. or link to an issue that includes them.

**Review by nimbinatus — APPROVED** [review]
Love it! LGTM from a quick rundown as it looks the same as the existing content, just in sphinx/RST

**Pull request merged**
