### PR TITLE
Fix examples for Random provider intro.

### PR DESCRIPTION
**Pull request by clstokes**
Method and args name was wrong per https://www.pulumi.com/docs/reference/pkg/random/randompet/#create.

### CODE REVIEW

**Review by stack72 — APPROVED** [review]
Thank you!!!

**Comment by lukehoban** [comment]
This needs to be fixed in all other languages as well - right?

**Comment by clstokes** [comment]
> This needs to be fixed in all other languages as well - right?

Yea, you're right. I'll fix them too...

**Comment by clstokes** [comment]
Fixed the rest of them.

**Review by lukehoban — APPROVED** [review]

**Pull request merged**
