### PR TITLE
Regenerate tutorials

### PR DESCRIPTION
**Pull request by cnunciato**
This is the result of running `scripts/mktutorial.sh`, mainly to fix some links in READMEs causing our link-checker to complain.

### CODE REVIEW

**Comment by davidwrede** [comment]
Looks like we have some formatting issues with some of the READMEs.

The readme for the [Wordpress tutorial](http://pulumi-docs-origin-pr-5290-ed19c040.s3-website.us-west-2.amazonaws.com/docs/tutorials/aws/aws-py-wordpress-fargate-rds/) doesn't seem to increment the step numbering (as shown in the original README). 

Also, I've seen where some output code blocks don't render correctly for some reason (maybe it's a whitespace issue?). See step four in http://pulumi-docs-origin-pr-5290-ed19c040.s3-website.us-west-2.amazonaws.com/docs/tutorials/aws/aws-ts-apigatewayv2-http-api-quickcreate/ for an example.

**Comment by lukehoban** [comment]
> Looks like we have some formatting issues with some of the READMEs.

I believe this is https://github.com/pulumi/docs/issues/1091 (and the other issues linked to it)?

**Review by davidwrede — APPROVED** [review]
My observations line up with those discussed in #1091. Since that issue is already those rendering problems, this PR is gtg.

**Comment by cnunciato** [comment]
Great, thanks y'all. I'll give the linked issue a follow-up look today.

**Pull request merged**
