### PR TITLE
WIP - Filter out BLC log spam

### PR DESCRIPTION
**Pull request by chrsmith**
Trying to see if this works for filtering out blog log spam from `https://github.com/stevenvachon/broken-link-checker/issues/133`.

### CODE REVIEW

**Comment by justinvp** [comment]
It looks like the next version of the BLC (v0.8.0) is going to have a `verbosity` flag where you can set it to only show broken links. https://github.com/stevenvachon/broken-link-checker/blob/512431eb48f6bebd837ed008a1df79b74094d76d/lib/cli.js#L505-L511. But it hasn't been released/published yet.

**Comment by justinvp** [comment]
I keep waiting for the BLC v0.8.0 to be released on npm... In the meantime, we could just start using  `v0.8.0-alpha` (which is prob fine for our use; yolo) via `yarn add https://github.com/stevenvachon/broken-link-checker#60ffc06c8d5b790c4ad160eddd8f7059454af0c9`. Then we can add `--verbosity 0` to only output broken links.

I started working on a PR to do that, but v0.8.0 drops support for Node versions below 12.0 and I'm still running Node v8.11.2 on this machine and don't want to mess with that right now.

**Comment by justinvp** [comment]
I want to look into possibly switching us over to https://github.com/wjdp/htmltest

**Comment by chrsmith** [comment]
@justinvp re: switching from `bloc` to `htmltest`, that sounds like a good improvement. Since assuming it does as good of a job for broken link detection, we'd be getting more coverage as well. /cc @zchase , who might be interested as well as our linting/validation relates to SEO.

**Comment by chrsmith** [comment]
As for as keeping the repo tidy and what not, I'll go ahead and close this PR out though.

**Pull request closed without merging**
