### PR TITLE
Remove superfluous package authoring page.

### PR DESCRIPTION
**Pull request by jkodroff**

### CODE REVIEW

**Comment by jkodroff** [comment]
@pulumi/docs Still waiting on a review on this. Note that the main registry page links to the page I want to remove: https://www.pulumi.com/registry/

Do I need to fix that somewhere else?

**Review by sean1588 — APPROVED** [review]
Leaving my approval here as this makes sense to me. I'm not part of the docs team github group so not sure if you will need to wait for a review from one of them.

**Comment by sean1588** [comment]
> Do I need to fix that somewhere else?

@jkodroff - I opened a PR to update registry here: https://github.com/pulumi/registry/pull/5258

I also pushed a commit to this PR to redirect from the deleted page roure

**Review by interurban — APPROVED** [review]
thx Josh

**Pull request merged**
