### PR TITLE
additional instructions to go quick start and update to go landing page

### PR DESCRIPTION
**Pull request by spara**
### Proposed changes

Added instructions for GOPATH to quick starts, updated Go link on languages landing page, added link to godocs on go.md

### CODE REVIEW

**Comment by cnunciato** [comment]
@spara Are you planning to revisit this, or would you like to close?

**Comment by susanev** [comment]
this work is planned to be revisited after @davidwrede's updates to the getting started guides

**Comment by cnunciato** [comment]
Can we close this and move it to pulumi-hugo?

**Comment by spara** [comment]
not published

**Pull request closed without merging**
