### PR TITLE
Add missing golang example for sshkey.md

### PR DESCRIPTION
**Pull request by dirien**
### Proposed changes

Add missing golang example for sshkey.md

image

### CODE REVIEW

**Comment by leezen** [comment]
Thanks for the submission! The examples are code generated, so I think we'd need to do something extra here to preserve this on subsequent updates. @stack72 is there any mechanism for doing so?

**Comment by dirien** [comment]
hi @leezen , any news on this one? 😄

**Comment by stack72** [comment]
Hi @dirien 

I'm working on a mechanism in https://github.com/pulumi/pulumi-terraform-bridge/issues/364 to allow this to happen :)

P.

**Comment by leezen** [comment]
I'll close out this PR as we'll want to submit the example against a different repo.

**Pull request closed without merging**
