### PR TITLE
Master to production doc PR.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by lukehoban** [comment]
@justinvp @chrsmith @cnunciato Is it intentional there is so much stuff to merge here?  Or is this because we recently moved to master being production - and just need to update process docs in the wiki to align with that?

**Comment by justinvp** [comment]
Doing this is no longer necessary. Any changes to `master` are now deployed to `production`. We should just delete the `production` branch.

**Comment by justinvp** [comment]
> and just need to update process docs in the wiki to align with that

I'll update the wiki.

**Comment by CyrusNajmabadi** [comment]
Note: the docs say this: https://github.com/pulumi/home/wiki/Producing-an-SDK#listing-a-new-cli-release-and-updating-documentation

> Merge your changes into master. Then, create a new PR to merge master into production using a Merge commit (required).

Can you update them @justinvp to whatever is accurate now?

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by justinvp** [comment]
Done.

**Pull request closed without merging**
