### PR TITLE
Create HttpBlog.md

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @lukehoban @mehzer @joeduffy .  Feel free to tear apart.  Also, this is just a PR.  So if you feel strongly about anything, just go in and make the edits yourself :)   We can treat this as a collaborative document.

Thanks!

**Comment by mehzer** [comment]
lgtm. i'll add closing links to serverless bits and pieces at the bottom before publish.

**Comment by daveremy** [comment]
Hey Cyrus, I put some minor editing changes up there in a commit.  All of the changes were pretty nit so please feel free to ignore.  There were a couple of mispellings I probably should have just called out separately.  It is a really good post, game changing stuff!

**Comment by CyrusNajmabadi** [comment]
Oh no.  *Please* just correct mispellings as you see them.  it's much faster than having to write them up and have someone else go edit it :D

Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out as Marc has moved to appropriate online location.

**Pull request closed without merging**
