### PR TITLE
Move "On this Page" feature to right nav

### PR DESCRIPTION
**Pull request by bermudezmt**
Signed-off-by: bermudezmt <bermudez.mt@gmail.com>

### Proposed changes

  - Disabled for home but will need to be disabled for other content types
  - Needs additional styling, plus consider making the navigation fixed

### Related issues (optional)

Addresses #927

### CODE REVIEW

**Comment by bermudezmt** [comment]
@cnunciato This is what it looks like at the moment. May need your help with the following: Applying indentation to H3 elements, and sticky positioning for the right TOC. I wanted to see if this is a good general direction. 

@justinvp I experimented with Hugo's `TableofContents` feature, but this seems like the cleanest quickest way to implement this change for now.

Screenshot from 2019-07-24 11-45-38

**Comment by cnunciato** [comment]
I'm seeing the menu appear on the right-hand side of pages that don't have the content to support it. Can we suppress it in these situations? Happy to help here if you like.

**Comment by bermudezmt** [comment]
Yes, happy to take the help as I'm back to content focus for the rest of the week. Thanks, @cnunciato

**Comment by justinvp** [comment]
@bermudezmt, I've made some changes to get this into shape and address @cnunciato's feedback. I'll push a commit or two soon.

**Comment by justinvp** [comment]
I pushed a commit with various improvements. I believe this is in a good enough state to merge (modulo any feedback), and we can iterate further subsequently (e.g. making it sticky as you scroll). @bermudezmt, @cnunciato, please take a look.

**Comment by bermudezmt** [comment]
Thank you for the improvements, @justinvp . I noted some follow-up work we have to do on https://github.com/pulumi/docs/issues/1325 but I agree, this is good to merge and will be a helpful addition. :)

**Pull request merged**
