### PR TITLE
aws.route53.Record.type expects RecordTypes

### PR DESCRIPTION
**Pull request by albestia**

### CODE REVIEW

**Comment by stack72** [comment]
I believe the PR I am working on will solve this - I will let you know if it’s the case

**Comment by ellismg** [comment]
Thanks for the contribution, @albestia!

This won't work as is, I think, because the examples are auto-generated by converting some existing code using `tf2pulumi`.  @pgavlin do you know how this is supposed to work in tf2pulumi?  Should we have been typing these things as `RecordType | string` in the TS layer so the above would have continued to work?  /cc @CyrusNajmabadi @stack72

**Comment by pgavlin** [comment]
> Should we have been typing these things as `RecordType | string` in the TS layer so the above would have continued to work?

Yes, this seems like the right thing to do.

**Comment by CyrusNajmabadi** [comment]
Yup.  Seems reasonable.  @stack72 do you want to take this?

**Comment by stack72** [comment]
FYI, I have made a fix in pulumi-aws that changes the behaviour here to what @ellismg / @pgavlin suggested

**Pull request closed without merging**
