### PR TITLE
Add createOptions for azure managed disks

### LINKED ISSUE #5371: Azure ManagedDisk createOptions does not contain possible values.
File: [docs/reference/pkg/azure/compute/manageddisk.md](https://www.pulumi.com/docs/reference/pkg/azure/compute/manageddisk/)

The docs on createOption parameter do not list the possible values. Those values can be found here: https://docs.microsoft.com/en-us/rest/api/compute/disks/createorupdate#diskcreateoption

### PR DESCRIPTION
**Pull request by codedevote**
### Proposed changes

Added missing values for azure managed disk createOptions Input.

### Related issues (optional)
 Fixes #5371

### CODE REVIEW

**Comment by cnunciato** [comment]
@davidwrede @mikhailshilkov Is there something we can do to get this change into the proper place?

**Comment by mikhailshilkov** [comment]
@codedevote Thank you for your time to open this PR, sorry we missed it.

Unfortunately, this page is auto-generated from Microsoft's Open API specs, so we can't edit it manually. Any change would need to be made upstream in https://github.com/Azure/azure-rest-api-specs

**Comment by mikhailshilkov** [comment]
I'm sorry, my bad again, we generate it from the upstream Terraform provider https://github.com/terraform-providers/terraform-provider-azurerm

**Comment by codedevote** [comment]
@mikhailshilkov No worries, I just found that the PR/fix has made its way. Next time I have such a docs issue i'll ask in community slack first, so you can direct me to the correct repo to open the issue.

**Pull request closed without merging**
