### PR TITLE
Change order of language list to match sidebar.

### PR DESCRIPTION
**Pull request by clstokes**
Changes order of languages to match the sidebar, https://www.pulumi.com/docs/intro/languages/:

image

### CODE REVIEW

**Comment by clstokes** [comment]
http://pulumi-docs-origin-pr-4969-a1656cf6.s3-website.us-west-2.amazonaws.com/docs/intro/languages/

image

**Review by davidwrede — APPROVED** [review]

**Comment by lukehoban** [comment]
We should definitely fix this - but I suspect we should align with the order in the prose instead of the order in the TOC (which I think was accidental).  This order should match the size and completeness of current or near future user bases - and the TOC order is almost exactly backward for that unfortunately.

I'd suggest either:
* Node.js 
* Python 
* .NET Core
* Go

Or:
* Python 
* Node.js 
* .NET Core
* Go

**Comment by cnunciato** [comment]
I'll push a commit to fix the menu ordering to match what Luke suggests to finish this up.

**Review by davidwrede — APPROVED** [review]
Approving the new changes

**Pull request merged**
