### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by eduherminio**
### Proposed changes

Fix typo in variable name (`hmtlString` -> `htmlString`).

### CODE REVIEW

**Review by stack72 — APPROVED** [review]
Thanks so much for this!!

**Comment by eduherminio** [comment]
@stack72 Are you fixing this via another commit?

**Comment by stack72** [comment]
@eduherminio yes, I will make sure you get the commit attribution - this is because the build is failing from a community PR for some reason :/

**Comment by eduherminio** [comment]
Oh, don't worry about that 😂😂

**Pull request closed without merging**
