### PR TITLE
Add Terraform PPC page 

### PR DESCRIPTION
**Pull request by zchase**
https://github.com/pulumi/home/issues/660

### CODE REVIEW

**Comment by cnunciato** [comment]
@zchase what's needed to finish this off, assuming it's still relevant? Can I help get it finished up?

**Comment by zchase** [comment]
@cnunciato A review was all this needed, but now that `stencil.js` is a thing we probably want to implement the JS in `stencil` instead of `jQuery`, right?

**Comment by cnunciato** [comment]
Probably, but I'd also like to talk through this a bit more so I can help out with the overall UX.

**Comment by cnunciato** [comment]
@zchase Can we close this PR and revisit collaboratively on a replacement?

**Comment by zchase** [comment]
@cnunciato Yeah let's mark it as closed and come back. There are no near-term plans to use the page currently, though we should revisit this and `/terraform`.

**Pull request closed without merging**
